spring.application.name=sistema-reportes-mantenimiento

# Perfil activo para trabajar en nuestra computadora
spring.profiles.active=dev

# Página de error personalizada
server.error.whitelabel.enabled=false