# Perfil PROD: PostgreSQL en Neon
# Este perfil NO se utiliza todavía.

# Las credenciales se recibirán mediante variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Conserva y actualiza la estructura de la base de datos
spring.jpa.hibernate.ddl-auto=update

# No mostrar SQL en producción
spring.jpa.show-sql=false

# La consola H2 debe estar desactivada en producción
spring.h2.console.enabled=false